defaults:
  - _self_
  - model: seconformer
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

## Dataset related
## Note! The length of a data is (segment - shift)
## The number of data you get from one audio is (audio_length - segment) // shift
sampling_rate: 16000  
segment: 64000        
stride: 32000         
shift: 32000

batch_size: 16
batch_size_valid: 16
epochs: 200

# True if you want to evaluate only
eval_only: true     
eval_every: 200
eval_stt: true

## Loss related
## Note! The supported loss functions are:
## l1_loss, l2_loss, multistftloss, timefreq_loss
loss:
  l1_loss: 1.0
  multistftloss:
    weight: 1.0
    factor_mag: 0.5
    factor_sc: 0.5
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    window: hann_window

## Optimization related
## Note! The supported optimizers are: adam, adamw
lr: 3e-4
optim: adam
betas: [0.9, 0.99]
clip_grad_norm: 1

## Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5
ddp:
  master_addr: localhost
  master_port: 12355

checkpoint: true
checkpoint_file: checkpoint.th  
continue_from:
samples_dir: samples
log_dir: tensorbd

## Other stuff
seed: 2035

## Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs
    subdir: ${hydra.job.override_dirname}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr