defaults:
  - _self_
  - model: seconformer
  - api: clova_api
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

dset:
  train: dataset/trainfiles.txt  # path to train folder
  valid: dataset/validfiles.txt  # path to valid folder.

# Dataset related
sampling_rate: 16000
segment: 64000
stride: 32000
shift: 32000

batch_size: 16
epochs: 200

# Evaluation only
eval_only: 
eval_every: 200  # compute test metrics every so epochs
eval_stt: true
transcripts: /home/user114/yunsik/dataset/transcripts.txt

# Loss related
loss:
  l1: 1.0
  multistftloss:
    weight: 1.0
    factor_mag: 0.5
    factor_phase: 0.5
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    window: hann_window

# Optimization related
lr: 3e-4
optim: adam
betas: [0.9, 0.99]

# Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5

# Checkpointing, by default automatically load last checkpoint
checkpoint_model:

checkpoint: true
checkpoint_file: checkpoint.th
continue_from: 
samples_dir: samples
log_dir: tensorbd

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs
    subdir: ${hydra.job.override_dirname}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr

  hydra_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr